Settings:
  Version: '2.11.2a+'
  Log-Creator: true
  SubData:
    Address: '127.0.0.1:4391'
    Password: 'password123'
    Allowed-Connections: []

Hosts:
  '~Built-In':
    Enabled: true
    Driver: 'BUILT-IN'
    Address: '127.0.0.1'
    Directory: './'
    Git-Bash: 'C:\Program Files\Git'

Servers:
  'Server_1':
    Enabled: false
    Host: '~Built-In'
    Port: 25566
    Motd: '&aThis is a SubServer'
    Log: true
    Directory: './Server_1'
    Executable: 'java -Djline.terminal=jline.UnsupportedTerminal -jar Spigot.jar'
    Stop-Command: 'stop'
    Run-On-Launch: false
    Auto-Restart: false
    Restricted: false
    Hidden: false