Settings:
  Version: '2.11.2a+'
  Log-Creator: true
  SubData:
    Address: '127.0.0.1:4391'
    Password: ''
    Allowed-Connections: []

Hosts:
  '~':
    Enabled: true
    Driver: 'BUILT-IN'
    Address: '127.0.0.1'
    Directory: './'
    Git-Bash: 'C:\Program Files\Git'

Servers:
  'Example':
    Enabled: false
    Host: '~'
    Port: 25567
    Motd: '&aThis is a SubServer'
    Log: true
    Directory: './Example'
    Executable: 'java -Djline.terminal=jline.UnsupportedTerminal -jar Spigot.jar'
    Stop-Command: 'stop'
    Run-On-Launch: false
    Auto-Restart: false
    Restricted: false
    Hidden: false