Settings:
  Version: '2.11.2a+'
  Log-Creator: true
  Override-Bungee-Commands: true
  UPnP:
    Forward-Proxy: true
    Forward-SubData: false
    Forward-Servers: false
  SubData:
    Address: '127.0.0.1:4391'
    Password: 'default'
    Encryption: 'AES'
    Allowed-Connections: []

Hosts:
  '~':
    Enabled: true
    Display: 'Default'
    Driver: 'BUILT-IN'
    Address: '127.0.0.1'
    Port-Range: '25500-25559'
    Directory: './SubServers/Servers'
    Git-Bash: '%ProgramFiles%\Git'

Servers:
  'Example':
    Enabled: false
    Display: ''
    Host: '~'
    Group: []
    Port: 25567
    Motd: '&aThis is a SubServer'
    Log: true
    Directory: './Example'
    Executable: 'java -Djline.terminal=jline.UnsupportedTerminal -jar Spigot.jar'
    Stop-Command: 'stop'
    Stop-Action: 'NONE'
    Run-On-Launch: false
    Restricted: false
    Incompatible: []
    Hidden: false