Settings:
  Version: '2.11.2a+'
  Console-Log: true
  Network-Log: true
  Server-Bind: '127.0.0.1'
  UPnP:
    Forward-Servers: false
  SubData:
    Name: 'undefined'
    Address: '127.0.0.1:4391'
    Password: 'default'
    Encryption: 'AES'