Settings:
  Version: '2.11.2a+'
  Override-Bungee-Commands: true
  SubData:
    Address: '127.0.0.1:4391'
    Password: 'default'
    Encryption: 'AES'

Sync:
  Disabled-Commands: false
  Forced-Hosts: true
  MOTD: false
  Player-Limit: false
  Server-Priorities: true