Settings:
  Version: '2.11.2a+'
  Ingame-Access: true
  Show-Addresses: false
  Use-Title-Messages: true
  SubData:
    Name: 'undefined'
    Address: '127.0.0.1:4391'
    Password: 'default'
    Encryption: 'AES'