name: SubServers-Client-Bukkit
main: net.ME1312.SubServers.Client.Bukkit.SubPlugin
version: "2.16a"
authors: ["ME1312"]
softdepend: [TitleManager]
website: "https://github.com/ME1312/SubServers-2"
#commands:
#  subservers:
#    description: 'The SubServers Command'
#    usage: '/subservers is currently unavailable'
#  subserver:
#    description: 'The SubServers Command'
#    usage: '/subserver is currently unavailable'
#  sub:
#    description: 'The SubServers Command'
#    usage: '/sub is currently unavailable'
permissions:
  subservers.*:
    description: 'Grants Access to to Everything in SubServers.Client'
    default: op
    children:
      subservers.interface:
        description: 'Grants Access to the SubServers Interface'
        default: op
      subservers.command:
        description: 'Grants Access to the SubServers Command'
        default: op
      subservers.host.*:
        description: 'Grants Access to all Host Actions on all Hosts'
        default: op
        children:
          subservers.host.*.*:
            description: 'Grants Access to all Host Actions on all Hosts'
            default: op
            children:
              subservers.host.*.create:
                description: 'Grants Access to Create a SubServer on all Hosts'
                default: op
      subservers.subserver.*:
        description: 'Grants Access to all SubServer Actions on all SubServers'
        default: op
        children:
          subservers.subserver.*.*:
            description: 'Grants Access to all SubServer Actions on all SubServers'
            default: op
            children:
              subservers.subserver.*.start:
                description: 'Grants Access to Start all SubServers'
                default: op
              subservers.subserver.*.stop:
                description: 'Grants Access to Stop all SubServers'
                default: op
              subservers.subserver.*.terminate:
                description: 'Grants Access to Terminate all SubServers'
                default: op
              subservers.subserver.*.command:
                description: 'Grants Access to Send Commands to all SubServers'
                default: op
              subservers.subserver.*.update:
                description: 'Grants Access to Update all SubServers'
                default: op
      subservers.server.*:
        description: 'Grants Access to Server Actions on all Servers'
        default: op
        children:
          subservers.server.*.*:
            description: 'Grants Access to Server Actions on all Servers'
            default: op
            children:
              subservers.server.*.teleport:
                description: 'Grants Access to Teleport to any Server'
                default: op
              subservers.server.*.teleport-others:
                description: 'Grants Access to Teleport Others to any Server'
                default: op